### ISSUE TITLE
Publish source code

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.travel#2]
See https://github.com/TWiStErRob/TWiStErRob-env/blob/master/svn2git-migration/conf/monorepo-split-net.twisterrob.travel.rules for more details.

It seems also part of this history.
 - Libraries\android_google-play-services_lib\
 - Libraries\android_google-play-services_lib_froyo\ ?
 - Libraries\android_support-v7_appcompat\

### Tasks
- [x] Create issue in target repo
- [x] Link it here
- [x] Clean up local copy
- [x] Use svn2git
- [x] Renormalize line endings with .gitattributes ([example](https://github.com/TWiStErRob/net.twisterrob.inventory/commit/d26197f7247ab29bdd9b4bb4a2b86832eea013d4))
- [x] Replace svn:externals with a submodule ([example](https://github.com/TWiStErRob/net.twisterrob.inventory/commit/8331db992b746308b5d97c200bc4f1eb142f179e))
- [ ] Optional: Build CI
- [x] Delete from SVN
- [x] Replace p:\projects\workspace\x (.svn) with p:\project\workspace\repo.name.x (.git)
- [x] Create tag svn for the last SVN commit in git, and create a pre-release on GitHub: "SVN to GIT migration" and description: "This is the point of the last commit in SVN. After this commits went to GitHub git."
- [x] recreate/tag existing releases on GH
- [ ] link new releases from website (see [guide](https://github.com/TWiStErRob/.github/blob/main/RELEASE.md))
- [x] tick the box in split epic
