### ISSUE TITLE
Epic: Tech upgrade

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.travel#5]
- [x] #2
 - [x] #4
 - [x] Bump AGP, Gradle to latest-ish: #6 + #39
 - [x] Upgrade AppEngine to latest: #7
 - [x] Version Catalogs and Build improvements: #8 + #22
 - [x] Fix all lint warnings (+ enable lint on :Shared), remove abortOnError: #16 + #26
 - [x] Review all Java deprecation warnings (API 19-34): https://github.com/TWiStErRob/net.twisterrob.travel/pull/23
 - [ ] #180
 - [x] #45
 - [x] #12 + #25
 - [x] #11 -> #38
 - [x] Rename modules: #30, #37
 - [x] Split up two apps: #30
 - [x] #13
 - [x] #18
 - [x] https://github.com/TWiStErRob/net.twisterrob.travel/issues/21
 - [x] #29
 - [x] https://github.com/TWiStErRob/net.twisterrob.travel/pull/30#discussion_r1421833640
 - [x] #58 
 - [x] #59
 - [x] #49
